config/routes.rb
Rails.application.routes.draw do
  get "documentaryfilms/index"
  get "documentaryfilms/create"
  get "documentaryfilms/new"
  get "series/index"
  get "series/create"
  get "series/new"
  get "movies/index"
  get "movies/create"
  get "movies/new"

  post "movies", to:"movies#create"
  post "series",  to:"series#create"
  post "documentary_films",  to:"documentaryfilms#create"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "movies#new"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/documentary_film.rb
class DocumentaryFilm < ApplicationRecord
    validates :name, :synopsis, :director, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
    validates :name, :synopsis, :director, presence: true
end

app/models/serie.rb
class Serie < ApplicationRecord
    validates :name, :synopsis, :director, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/documentaryfilms_controller.rb
class DocumentaryfilmsController < ApplicationController
  def index
    @documentary_film = DocumentaryFilm.all
  end

  def create
    @documentary_film = DocumentaryFilm.new(documentaryfilms_params)
    
    if @documentary_film.save
      redirect_to documentaryfilms_index_path
    else
      render :new
    end
  end

  def new
    @documentary_film = DocumentaryFilm.new
  end

  private

  def documentaryfilms_params
    params.require(:documentary_film).permit(:name, :synopsis, :director)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movie = Movie.all
  end

  def create
    @movie = Movie.new(movies_params)
    
    if @movie.save
      redirect_to movies_index_path
    else
      render :new
    end
  end

  def new
    @movie = Movie.new
  end

  private

  def movies_params
    params.require(:movie).permit(:name, :synopsis, :director)
  end
end

app/controllers/series_controller.rb
class SeriesController < ApplicationController
  def index
    @serie = Serie.all
  end

  def create
    @serie = Serie.new(series_params)
    
    if @serie.save
      redirect_to series_index_path
    else
      render :new
    end
  end

  def new
    @serie = Serie.new
  end
  private

  def series_params
    params.require(:serie).permit(:name, :synopsis, :director)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documentaryfilms_helper.rb
module DocumentaryfilmsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/series_helper.rb
module SeriesHelper
end

app/views/documentaryfilms/create.html.erb
<h1>Documentaryfilms#create</h1>
<p>Find me in app/views/documentaryfilms/create.html.erb</p>

app/views/documentaryfilms/index.html.erb
<div class="container">
    <h1 class="text-center my-5">Mostrando los Documentary Films</h1>
    <% @documentary_film.each do |p| %>
    <h2><%= p.name %></h2>
    <p><%= p.synopsis %></p>
    <p><%= p.director %></p>
    <% end%>
    <%= link_to "Agregar un nuevo Documentary Film", documentaryfilms_new_path %>
</div>

app/views/documentaryfilms/new.html.erb
<div class="container">
    <h1 class="text-center display-5">Documentary films</h1>
    
        <%= form_with model: @documentary_film, method: :post do |form| %>
        <div class="container">
            <%= form.label :name, "Name", class: "form-label" %>
            <%= form.text_field :name, class: "form-control" %>
        </div>
        <div class="container">
            <%= form.label :synopsis, "Synopsis", class: "form-label" %>
            <%= form.text_field :synopsis, class: "form-control" %>   
        </div>
        <div class="container">
            <%= form.label :director, "Director", class: "form-label" %>
            <%= form.text_field :director, class: "form-control" %>   
        </div>
        <div class="container my-5">
            <%= form.submit "Crear", class: "btn btn-primary" %>
        </div>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "App Peliculas" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
      <div class="container">
        <a class="navbar-brand" href="#">Plataforma de Películas</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav ms-auto">
            <%= link_to 'Movies', root_path, class:'nav-link active', ariaCurrent: 'page' %>
            <%= link_to 'Series', series_new_path, class:'nav-link active' %>
            <%= link_to 'Documentary Films', documentaryfilms_new_path, class:'nav-link active' %>
          </div>
        </div>
      </div>
    </nav>

  <div class="container">
  
      <%= yield %>
  </div>


  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
  </body>
</html>

app/views/movies/create.html.erb
<h1>Movies#create</h1>
<p>Find me in app/views/movies/create.html.erb</p>

app/views/movies/index.html.erb
<div class="container">
    <h1 class="text-center my-5">Mostrando las Movies</h1>
    <% @movie.each do |p| %>
    <h2><%= p.name %></h2>
    <p><%= p.synopsis %></p>
    <p><%= p.director %></p>
    <% end%>
    <%= link_to "Agregar nueva Movie", movies_new_path %>
</div>

app/views/movies/new.html.erb
<div class="container">
    <h1 class="text-center display-5">Movies</h1>
    
        <%= form_with model: @movie, method: :post do |form| %>
        <div class="container">
            <%= form.label :name, "Name", class: "form-label" %>
            <%= form.text_field :name, class: "form-control" %>
        </div>
        <div class="container">
            <%= form.label :synopsis, "Synopsis", class: "form-label" %>
            <%= form.text_field :synopsis, class: "form-control" %>   
        </div>
        <div class="container">
            <%= form.label :director, "Director", class: "form-label" %>
            <%= form.text_field :director, class: "form-control" %>   
        </div>
        <div class="container my-5">
            <%= form.submit "Crear", class: "btn btn-primary" %>
        </div>
    <% end %>
</div>

app/views/series/create.html.erb
<h1>Series#create</h1>
<p>Find me in app/views/series/create.html.erb</p>

app/views/series/index.html.erb
<div class="container">
    <h1 class="text-center my-5">Mostrando las Series</h1>
    <% @serie.each do |p| %>
    <h2><%= p.name %></h2>
    <p><%= p.synopsis %></p>
    <p><%= p.director %></p>
    <% end%>
    <%= link_to "Agregar nueva Serie", series_new_path %>
</div>

app/views/series/new.html.erb
<div class="container">
    <h1 class="text-center display-5">Series</h1>
    
        <%= form_with model: @serie, method: :post do |form| %>
        <div class="container">
            <%= form.label :name, "Name", class: "form-label" %>
            <%= form.text_field :name, class: "form-control" %>
        </div>
        <div class="container">
            <%= form.label :synopsis, "Synopsis", class: "form-label" %>
            <%= form.text_field :synopsis, class: "form-control" %>   
        </div>
        <div class="container">
            <%= form.label :director, "Director", class: "form-label" %>
            <%= form.text_field :director, class: "form-control" %>   
        </div>
        <div class="container my-5">
            <%= form.submit "Crear", class: "btn btn-primary" %>
        </div>
    <% end %>
</div>